//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.25 at 01:33:12 PM EET 
//


package ro.uti.ksme.wps.wps2.pojo.ows._2;

import ro.uti.ksme.wps.wps2.pojo.w3._1999.xlink.ActuateType;
import ro.uti.ksme.wps.wps2.pojo.w3._1999.xlink.ShowType;

import javax.xml.bind.annotation.*;


/**
 * This type contains only a restricted and annotated set of
 * the attributes from the xlink:simpleAttrs attributeGroup.
 *
 *
 * <p>Java class for AbstractReferenceBaseType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AbstractReferenceBaseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" fixed="simple" /&gt;
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}href use="required""/&gt;
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}role"/&gt;
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}arcrole"/&gt;
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}title"/&gt;
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}show"/&gt;
 *       &lt;attribute ref="{http://www.w3.org/1999/xlink}actuate"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractReferenceBaseType")
@XmlSeeAlso({
        ReferenceType.class
})
public class AbstractReferenceBaseType {

    /**
     *
     *
     */
    @XmlAttribute(name = "type", namespace = "http://www.opengis.net/ows/2.0")
    public final static String TYPE = "simple";
    @XmlAttribute(name = "href", namespace = "http://www.w3.org/1999/xlink", required = true)
    protected String href;
    @XmlAttribute(name = "role", namespace = "http://www.w3.org/1999/xlink")
    protected String role;
    @XmlAttribute(name = "arcrole", namespace = "http://www.w3.org/1999/xlink")
    protected String arcrole;
    @XmlAttribute(name = "title", namespace = "http://www.w3.org/1999/xlink")
    protected String title;
    @XmlAttribute(name = "show", namespace = "http://www.w3.org/1999/xlink")
    protected ShowType show;
    @XmlAttribute(name = "actuate", namespace = "http://www.w3.org/1999/xlink")
    protected ActuateType actuate;

    /**
     * Reference to a remote resource or local payload. A
     * remote resource is typically addressed by a URL. For a local payload
     * (such as a multipart mime message), the xlink:href must start with the
     * prefix cid:.
     *
     * @return possible object is
     * {@link String }
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setHref(String value) {
        this.href = value;
    }

    public boolean isSetHref() {
        return (this.href != null);
    }

    /**
     * Reference to a resource that describes the role of this
     * reference. When no value is supplied, no particular role value is to
     * be inferred.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRole(String value) {
        this.role = value;
    }

    public boolean isSetRole() {
        return (this.role != null);
    }

    /**
     * Although allowed, this attribute is not expected to be
     * useful in this application of xlink:simpleAttrs.
     *
     * @return possible object is
     * {@link String }
     */
    public String getArcrole() {
        return arcrole;
    }

    /**
     * Sets the value of the arcrole property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setArcrole(String value) {
        this.arcrole = value;
    }

    public boolean isSetArcrole() {
        return (this.arcrole != null);
    }

    /**
     * Describes the meaning of the referenced resource in a
     * human-readable fashion.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTitle(String value) {
        this.title = value;
    }

    public boolean isSetTitle() {
        return (this.title != null);
    }

    /**
     * Although allowed, this attribute is not expected to be
     * useful in this application of xlink:simpleAttrs.
     *
     * @return possible object is
     * {@link ShowType }
     */
    public ShowType getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     *
     * @param value allowed object is
     *              {@link ShowType }
     */
    public void setShow(ShowType value) {
        this.show = value;
    }

    public boolean isSetShow() {
        return (this.show != null);
    }

    /**
     * Although allowed, this attribute is not expected to be
     * useful in this application of xlink:simpleAttrs.
     *
     * @return possible object is
     * {@link ActuateType }
     */
    public ActuateType getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     *
     * @param value allowed object is
     *              {@link ActuateType }
     */
    public void setActuate(ActuateType value) {
        this.actuate = value;
    }

    public boolean isSetActuate() {
        return (this.actuate != null);
    }

}
