//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.25 at 01:33:12 PM EET 
//


package ro.uti.ksme.wps.wps2.pojo.ows._2;

import ro.uti.ksme.wps.wps2.pojo.wps._2.WPSCapabilitiesType;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * XML encoded GetCapabilities operation response. This
 * document provides clients with service metadata about a specific service
 * instance, usually including metadata about the tightly-coupled data
 * served. If the server does not implement the updateSequence parameter,
 * the server shall always return the complete Capabilities document,
 * without the updateSequence parameter. When the server implements the
 * updateSequence parameter and the GetCapabilities operation request
 * included the updateSequence parameter with the current value, the server
 * shall return this element with only the "version" and "updateSequence"
 * attributes. Otherwise, all optional elements shall be included or not
 * depending on the actual value of the Contents parameter in the
 * GetCapabilities operation request. This base type shall be extended by
 * each specific OWS to include the additional contents
 * needed.
 *
 *
 * <p>Java class for CapabilitiesBaseType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CapabilitiesBaseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/2.0}ServiceIdentification" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/2.0}ServiceProvider" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/2.0}OperationsMetadata" minOccurs="0"/&gt;
 *         &lt;element name="Languages" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.opengis.net/ows/2.0}Language" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.opengis.net/ows/2.0}VersionType" /&gt;
 *       &lt;attribute name="updateSequence" type="{http://www.opengis.net/ows/2.0}UpdateSequenceType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CapabilitiesBaseType", propOrder = {
        "serviceIdentification",
        "serviceProvider",
        "operationsMetadata",
        "languages"
})
@XmlSeeAlso({
        WPSCapabilitiesType.class
})
public class CapabilitiesBaseType {

    @XmlElement(name = "ServiceIdentification")
    protected ServiceIdentification serviceIdentification;
    @XmlElement(name = "ServiceProvider")
    protected ServiceProvider serviceProvider;
    @XmlElement(name = "OperationsMetadata")
    protected OperationsMetadata operationsMetadata;
    @XmlElement(name = "Languages")
    protected CapabilitiesBaseType.Languages languages;
    @XmlAttribute(name = "version", required = true)
    protected String version;
    @XmlAttribute(name = "updateSequence")
    protected String updateSequence;

    /**
     * Gets the value of the serviceIdentification property.
     *
     * @return possible object is
     * {@link ServiceIdentification }
     */
    public ServiceIdentification getServiceIdentification() {
        return serviceIdentification;
    }

    /**
     * Sets the value of the serviceIdentification property.
     *
     * @param value allowed object is
     *              {@link ServiceIdentification }
     */
    public void setServiceIdentification(ServiceIdentification value) {
        this.serviceIdentification = value;
    }

    public boolean isSetServiceIdentification() {
        return (this.serviceIdentification != null);
    }

    /**
     * Gets the value of the serviceProvider property.
     *
     * @return possible object is
     * {@link ServiceProvider }
     */
    public ServiceProvider getServiceProvider() {
        return serviceProvider;
    }

    /**
     * Sets the value of the serviceProvider property.
     *
     * @param value allowed object is
     *              {@link ServiceProvider }
     */
    public void setServiceProvider(ServiceProvider value) {
        this.serviceProvider = value;
    }

    public boolean isSetServiceProvider() {
        return (this.serviceProvider != null);
    }

    /**
     * Gets the value of the operationsMetadata property.
     *
     * @return possible object is
     * {@link OperationsMetadata }
     */
    public OperationsMetadata getOperationsMetadata() {
        return operationsMetadata;
    }

    /**
     * Sets the value of the operationsMetadata property.
     *
     * @param value allowed object is
     *              {@link OperationsMetadata }
     */
    public void setOperationsMetadata(OperationsMetadata value) {
        this.operationsMetadata = value;
    }

    public boolean isSetOperationsMetadata() {
        return (this.operationsMetadata != null);
    }

    /**
     * Gets the value of the languages property.
     *
     * @return possible object is
     * {@link CapabilitiesBaseType.Languages }
     */
    public CapabilitiesBaseType.Languages getLanguages() {
        return languages;
    }

    /**
     * Sets the value of the languages property.
     *
     * @param value allowed object is
     *              {@link CapabilitiesBaseType.Languages }
     */
    public void setLanguages(CapabilitiesBaseType.Languages value) {
        this.languages = value;
    }

    public boolean isSetLanguages() {
        return (this.languages != null);
    }

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersion(String value) {
        this.version = value;
    }

    public boolean isSetVersion() {
        return (this.version != null);
    }

    /**
     * Gets the value of the updateSequence property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUpdateSequence() {
        return updateSequence;
    }

    /**
     * Sets the value of the updateSequence property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUpdateSequence(String value) {
        this.updateSequence = value;
    }

    public boolean isSetUpdateSequence() {
        return (this.updateSequence != null);
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.opengis.net/ows/2.0}Language" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "language"
    })
    public static class Languages {

        @XmlElement(name = "Language", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "language")
        protected List<String> language;

        /**
         * Gets the value of the language property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         */
        public List<String> getLanguage() {
            if (language == null) {
                language = new ArrayList<String>();
            }
            return this.language;
        }

        public boolean isSetLanguage() {
            return ((this.language != null) && (!this.language.isEmpty()));
        }

        public void unsetLanguage() {
            this.language = null;
        }

    }

}
