//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.25 at 01:33:12 PM EET 
//


package ro.uti.ksme.wps.wps2.pojo.ows._2;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * XML encoded GetCapabilities operation request. This
 * operation allows clients to retrieve service metadata about a specific
 * service instance. In this XML encoding, no "request" parameter is
 * included, since the element name specifies the specific operation. This
 * base type shall be extended by each specific OWS to include the
 * additional required "service" attribute, with the correct value for that
 * OWS.
 *
 *
 * <p>Java class for GetCapabilitiesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GetCapabilitiesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AcceptVersions" type="{http://www.opengis.net/ows/2.0}AcceptVersionsType" minOccurs="0"/&gt;
 *         &lt;element name="Sections" type="{http://www.opengis.net/ows/2.0}SectionsType" minOccurs="0"/&gt;
 *         &lt;element name="AcceptFormats" type="{http://www.opengis.net/ows/2.0}AcceptFormatsType" minOccurs="0"/&gt;
 *         &lt;element name="AcceptLanguages" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.opengis.net/ows/2.0}Language" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="updateSequence" type="{http://www.opengis.net/ows/2.0}UpdateSequenceType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetCapabilitiesType", propOrder = {
        "acceptVersions",
        "sections",
        "acceptFormats",
        "acceptLanguages"
})
@XmlSeeAlso({
        ro.uti.ksme.wps.wps2.pojo.wps._2.GetCapabilitiesType.class
})
public class GetCapabilitiesType {

    @XmlElement(name = "AcceptVersions")
    protected AcceptVersionsType acceptVersions;
    @XmlElement(name = "Sections")
    protected SectionsType sections;
    @XmlElement(name = "AcceptFormats")
    protected AcceptFormatsType acceptFormats;
    @XmlElement(name = "AcceptLanguages")
    protected GetCapabilitiesType.AcceptLanguages acceptLanguages;
    @XmlAttribute(name = "updateSequence")
    protected String updateSequence;

    /**
     * Gets the value of the acceptVersions property.
     *
     * @return possible object is
     * {@link AcceptVersionsType }
     */
    public AcceptVersionsType getAcceptVersions() {
        return acceptVersions;
    }

    /**
     * Sets the value of the acceptVersions property.
     *
     * @param value allowed object is
     *              {@link AcceptVersionsType }
     */
    public void setAcceptVersions(AcceptVersionsType value) {
        this.acceptVersions = value;
    }

    public boolean isSetAcceptVersions() {
        return (this.acceptVersions != null);
    }

    /**
     * Gets the value of the sections property.
     *
     * @return possible object is
     * {@link SectionsType }
     */
    public SectionsType getSections() {
        return sections;
    }

    /**
     * Sets the value of the sections property.
     *
     * @param value allowed object is
     *              {@link SectionsType }
     */
    public void setSections(SectionsType value) {
        this.sections = value;
    }

    public boolean isSetSections() {
        return (this.sections != null);
    }

    /**
     * Gets the value of the acceptFormats property.
     *
     * @return possible object is
     * {@link AcceptFormatsType }
     */
    public AcceptFormatsType getAcceptFormats() {
        return acceptFormats;
    }

    /**
     * Sets the value of the acceptFormats property.
     *
     * @param value allowed object is
     *              {@link AcceptFormatsType }
     */
    public void setAcceptFormats(AcceptFormatsType value) {
        this.acceptFormats = value;
    }

    public boolean isSetAcceptFormats() {
        return (this.acceptFormats != null);
    }

    /**
     * Gets the value of the acceptLanguages property.
     *
     * @return possible object is
     * {@link GetCapabilitiesType.AcceptLanguages }
     */
    public GetCapabilitiesType.AcceptLanguages getAcceptLanguages() {
        return acceptLanguages;
    }

    /**
     * Sets the value of the acceptLanguages property.
     *
     * @param value allowed object is
     *              {@link GetCapabilitiesType.AcceptLanguages }
     */
    public void setAcceptLanguages(GetCapabilitiesType.AcceptLanguages value) {
        this.acceptLanguages = value;
    }

    public boolean isSetAcceptLanguages() {
        return (this.acceptLanguages != null);
    }

    /**
     * Gets the value of the updateSequence property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUpdateSequence() {
        return updateSequence;
    }

    /**
     * Sets the value of the updateSequence property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUpdateSequence(String value) {
        this.updateSequence = value;
    }

    public boolean isSetUpdateSequence() {
        return (this.updateSequence != null);
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.opengis.net/ows/2.0}Language" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "language"
    })
    public static class AcceptLanguages {

        @XmlElement(name = "Language", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "language")
        protected List<String> language;

        /**
         * Gets the value of the language property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the language property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLanguage().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         */
        public List<String> getLanguage() {
            if (language == null) {
                language = new ArrayList<String>();
            }
            return this.language;
        }

        public boolean isSetLanguage() {
            return ((this.language != null) && (!this.language.isEmpty()));
        }

        public void unsetLanguage() {
            this.language = null;
        }

    }

}
