//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.25 at 01:33:12 PM EET 
//


package ro.uti.ksme.wps.wps2.pojo.ows._2;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProviderName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ProviderSite" type="{http://www.opengis.net/ows/2.0}OnlineResourceType" minOccurs="0"/&gt;
 *         &lt;element name="ServiceContact" type="{http://www.opengis.net/ows/2.0}ResponsiblePartySubsetType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "providerName",
        "providerSite",
        "serviceContact"
})
@XmlRootElement(name = "ServiceProvider")
public class ServiceProvider {

    @XmlElement(name = "ProviderName", required = true)
    protected String providerName;
    @XmlElement(name = "ProviderSite")
    protected OnlineResourceType providerSite;
    @XmlElement(name = "ServiceContact", required = true)
    protected ResponsiblePartySubsetType serviceContact;

    /**
     * Gets the value of the providerName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Sets the value of the providerName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProviderName(String value) {
        this.providerName = value;
    }

    public boolean isSetProviderName() {
        return (this.providerName != null);
    }

    /**
     * Gets the value of the providerSite property.
     *
     * @return possible object is
     * {@link OnlineResourceType }
     */
    public OnlineResourceType getProviderSite() {
        return providerSite;
    }

    /**
     * Sets the value of the providerSite property.
     *
     * @param value allowed object is
     *              {@link OnlineResourceType }
     */
    public void setProviderSite(OnlineResourceType value) {
        this.providerSite = value;
    }

    public boolean isSetProviderSite() {
        return (this.providerSite != null);
    }

    /**
     * Gets the value of the serviceContact property.
     *
     * @return possible object is
     * {@link ResponsiblePartySubsetType }
     */
    public ResponsiblePartySubsetType getServiceContact() {
        return serviceContact;
    }

    /**
     * Sets the value of the serviceContact property.
     *
     * @param value allowed object is
     *              {@link ResponsiblePartySubsetType }
     */
    public void setServiceContact(ResponsiblePartySubsetType value) {
        this.serviceContact = value;
    }

    public boolean isSetServiceContact() {
        return (this.serviceContact != null);
    }

}
