//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.08 at 01:22:16 PM EEST 
//


package ro.uti.ksme.wps.wps2_server.pojo.wps._2;

import javax.xml.bind.annotation.*;


/**
 * This type describes a process output in the execute response.
 *
 *
 * <p>Java class for DataOutputType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DataOutputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.opengis.net/wps/2.0}Data"/&gt;
 *           &lt;element ref="{http://www.opengis.net/wps/2.0}Reference"/&gt;
 *           &lt;element name="Output" type="{http://www.opengis.net/wps/2.0}DataOutputType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataOutputType", propOrder = {
        "data",
        "reference",
        "output"
})
public class DataOutputType {

    @XmlElement(name = "Data")
    protected Data data;
    @XmlElement(name = "Reference")
    protected ReferenceType reference;
    @XmlElement(name = "Output")
    protected DataOutputType output;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String id;

    /**
     * Gets the value of the data property.
     *
     * @return possible object is
     * {@link Data }
     */
    public Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     *
     * @param value allowed object is
     *              {@link Data }
     */
    public void setData(Data value) {
        this.data = value;
    }

    public boolean isSetData() {
        return (this.data != null);
    }

    /**
     * Gets the value of the reference property.
     *
     * @return possible object is
     * {@link ReferenceType }
     */
    public ReferenceType getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     *
     * @param value allowed object is
     *              {@link ReferenceType }
     */
    public void setReference(ReferenceType value) {
        this.reference = value;
    }

    public boolean isSetReference() {
        return (this.reference != null);
    }

    /**
     * Gets the value of the output property.
     *
     * @return possible object is
     * {@link DataOutputType }
     */
    public DataOutputType getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     *
     * @param value allowed object is
     *              {@link DataOutputType }
     */
    public void setOutput(DataOutputType value) {
        this.output = value;
    }

    public boolean isSetOutput() {
        return (this.output != null);
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    public boolean isSetId() {
        return (this.id != null);
    }

}
