//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.08 at 01:22:16 PM EEST 
//


package ro.uti.ksme.wps.wps2_server.pojo.wps._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Description of a process Output.
 * <p>
 * <p>
 * In this use, the DescriptionType shall describe a process output.
 *
 *
 * <p>Java class for GenericOutputType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GenericOutputType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/wps/2.0}DescriptionType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Output" type="{http://www.opengis.net/wps/2.0}GenericOutputType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericOutputType", propOrder = {
        "output"
})
public class GenericOutputType
        extends DescriptionType {

    @XmlElement(name = "Output")
    protected List<GenericOutputType> output;

    /**
     * Gets the value of the output property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the output property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutput().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericOutputType }
     */
    public List<GenericOutputType> getOutput() {
        if (output == null) {
            output = new ArrayList<GenericOutputType>();
        }
        return this.output;
    }

    public boolean isSetOutput() {
        return ((this.output != null) && (!this.output.isEmpty()));
    }

    public void unsetOutput() {
        this.output = null;
    }

}
