//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.08 at 01:22:16 PM EEST 
//


package ro.uti.ksme.wps.wps2_server.pojo.wps._2;

import ro.uti.ksme.wps.wps2_server.pojo.ows._2.*;

import javax.xml.bind.annotation.*;


/**
 * A literal data domain consists of a value type and range,
 * and optionally a unit of measurement and a default value.
 *
 *
 * <p>Java class for LiteralDataDomainType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LiteralDataDomainType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.opengis.net/ows/2.0}AllowedValues"/&gt;
 *           &lt;element ref="{http://www.opengis.net/ows/2.0}AnyValue"/&gt;
 *           &lt;element ref="{http://www.opengis.net/ows/2.0}ValuesReference"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/2.0}DataType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/2.0}UOM" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/2.0}DefaultValue" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LiteralDataDomainType", propOrder = {
        "allowedValues",
        "anyValue",
        "valuesReference",
        "dataType",
        "uom",
        "defaultValue"
})
@XmlSeeAlso({
        ro.uti.ksme.wps.wps2_server.pojo.wps._2.LiteralDataType.LiteralDataDomain.class
})
public class LiteralDataDomainType {

    @XmlElement(name = "AllowedValues", namespace = "http://www.opengis.net/ows/2.0")
    protected AllowedValues allowedValues;
    @XmlElement(name = "AnyValue", namespace = "http://www.opengis.net/ows/2.0")
    protected AnyValue anyValue;
    @XmlElement(name = "ValuesReference", namespace = "http://www.opengis.net/ows/2.0")
    protected ValuesReference valuesReference;
    @XmlElement(name = "DataType", namespace = "http://www.opengis.net/ows/2.0")
    protected DomainMetadataType dataType;
    @XmlElement(name = "UOM", namespace = "http://www.opengis.net/ows/2.0")
    protected DomainMetadataType uom;
    @XmlElement(name = "DefaultValue", namespace = "http://www.opengis.net/ows/2.0")
    protected ValueType defaultValue;

    /**
     * Gets the value of the allowedValues property.
     *
     * @return possible object is
     * {@link AllowedValues }
     */
    public AllowedValues getAllowedValues() {
        return allowedValues;
    }

    /**
     * Sets the value of the allowedValues property.
     *
     * @param value allowed object is
     *              {@link AllowedValues }
     */
    public void setAllowedValues(AllowedValues value) {
        this.allowedValues = value;
    }

    public boolean isSetAllowedValues() {
        return (this.allowedValues != null);
    }

    /**
     * Gets the value of the anyValue property.
     *
     * @return possible object is
     * {@link AnyValue }
     */
    public AnyValue getAnyValue() {
        return anyValue;
    }

    /**
     * Sets the value of the anyValue property.
     *
     * @param value allowed object is
     *              {@link AnyValue }
     */
    public void setAnyValue(AnyValue value) {
        this.anyValue = value;
    }

    public boolean isSetAnyValue() {
        return (this.anyValue != null);
    }

    /**
     * Gets the value of the valuesReference property.
     *
     * @return possible object is
     * {@link ValuesReference }
     */
    public ValuesReference getValuesReference() {
        return valuesReference;
    }

    /**
     * Sets the value of the valuesReference property.
     *
     * @param value allowed object is
     *              {@link ValuesReference }
     */
    public void setValuesReference(ValuesReference value) {
        this.valuesReference = value;
    }

    public boolean isSetValuesReference() {
        return (this.valuesReference != null);
    }

    /**
     * Gets the value of the dataType property.
     *
     * @return possible object is
     * {@link DomainMetadataType }
     */
    public DomainMetadataType getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     *
     * @param value allowed object is
     *              {@link DomainMetadataType }
     */
    public void setDataType(DomainMetadataType value) {
        this.dataType = value;
    }

    public boolean isSetDataType() {
        return (this.dataType != null);
    }

    /**
     * Gets the value of the uom property.
     *
     * @return possible object is
     * {@link DomainMetadataType }
     */
    public DomainMetadataType getUOM() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     *
     * @param value allowed object is
     *              {@link DomainMetadataType }
     */
    public void setUOM(DomainMetadataType value) {
        this.uom = value;
    }

    public boolean isSetUOM() {
        return (this.uom != null);
    }

    /**
     * Gets the value of the defaultValue property.
     *
     * @return possible object is
     * {@link ValueType }
     */
    public ValueType getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     *
     * @param value allowed object is
     *              {@link ValueType }
     */
    public void setDefaultValue(ValueType value) {
        this.defaultValue = value;
    }

    public boolean isSetDefaultValue() {
        return (this.defaultValue != null);
    }

}
