//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.08 at 01:22:16 PM EEST 
//


package ro.uti.ksme.wps.wps2_server.pojo.wps._2;

import org.w3c.dom.Element;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.opengis.net/wps/2.0}Process"/&gt;
 *           &lt;any processContents='lax' namespace='##other'/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.opengis.net/wps/2.0}processPropertiesAttributes"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "process",
        "any"
})
@XmlRootElement(name = "ProcessOffering")
public class ProcessOffering {

    @XmlElement(name = "Process")
    protected ProcessDescriptionType process;
    @XmlAnyElement(lax = true)
    protected Object any;
    @XmlAttribute(name = "jobControlOptions", required = true)
    protected List<String> jobControlOptions;
    @XmlAttribute(name = "outputTransmission")
    protected List<DataTransmissionModeType> outputTransmission;
    @XmlAttribute(name = "processVersion")
    protected String processVersion;
    @XmlAttribute(name = "processModel")
    protected String processModel;

    /**
     * Gets the value of the process property.
     *
     * @return possible object is
     * {@link ProcessDescriptionType }
     */
    public ProcessDescriptionType getProcess() {
        return process;
    }

    /**
     * Sets the value of the process property.
     *
     * @param value allowed object is
     *              {@link ProcessDescriptionType }
     */
    public void setProcess(ProcessDescriptionType value) {
        this.process = value;
    }

    public boolean isSetProcess() {
        return (this.process != null);
    }

    /**
     * Gets the value of the any property.
     *
     * @return possible object is
     * {@link Element }
     * {@link Object }
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     *
     * @param value allowed object is
     *              {@link Element }
     *              {@link Object }
     */
    public void setAny(Object value) {
        this.any = value;
    }

    public boolean isSetAny() {
        return (this.any != null);
    }

    /**
     * Gets the value of the jobControlOptions property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobControlOptions property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobControlOptions().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getJobControlOptions() {
        if (jobControlOptions == null) {
            jobControlOptions = new ArrayList<String>();
        }
        return this.jobControlOptions;
    }

    public boolean isSetJobControlOptions() {
        return ((this.jobControlOptions != null) && (!this.jobControlOptions.isEmpty()));
    }

    public void unsetJobControlOptions() {
        this.jobControlOptions = null;
    }

    /**
     * Gets the value of the outputTransmission property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputTransmission property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputTransmission().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataTransmissionModeType }
     */
    public List<DataTransmissionModeType> getOutputTransmission() {
        if (outputTransmission == null) {
            outputTransmission = new ArrayList<DataTransmissionModeType>();
        }
        return this.outputTransmission;
    }

    public boolean isSetOutputTransmission() {
        return ((this.outputTransmission != null) && (!this.outputTransmission.isEmpty()));
    }

    public void unsetOutputTransmission() {
        this.outputTransmission = null;
    }

    /**
     * Gets the value of the processVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProcessVersion() {
        return processVersion;
    }

    /**
     * Sets the value of the processVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProcessVersion(String value) {
        this.processVersion = value;
    }

    public boolean isSetProcessVersion() {
        return (this.processVersion != null);
    }

    /**
     * Gets the value of the processModel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProcessModel() {
        if (processModel == null) {
            return "native";
        } else {
            return processModel;
        }
    }

    /**
     * Sets the value of the processModel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProcessModel(String value) {
        this.processModel = value;
    }

    public boolean isSetProcessModel() {
        return (this.processModel != null);
    }

}
