//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.25 at 01:33:12 PM EET 
//


package ro.uti.ksme.wps.wps2.pojo.wps._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for GenericProcessType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GenericProcessType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/wps/2.0}DescriptionType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Input" type="{http://www.opengis.net/wps/2.0}GenericInputType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Output" type="{http://www.opengis.net/wps/2.0}GenericOutputType" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GenericProcessType", propOrder = {
        "input",
        "output"
})
public class GenericProcessType
        extends DescriptionType {

    @XmlElement(name = "Input")
    protected List<GenericInputType> input;
    @XmlElement(name = "Output", required = true)
    protected List<GenericOutputType> output;

    /**
     * Gets the value of the input property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the input property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInput().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericInputType }
     */
    public List<GenericInputType> getInput() {
        if (input == null) {
            input = new ArrayList<GenericInputType>();
        }
        return this.input;
    }

    public boolean isSetInput() {
        return ((this.input != null) && (!this.input.isEmpty()));
    }

    public void unsetInput() {
        this.input = null;
    }

    /**
     * Gets the value of the output property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the output property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutput().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenericOutputType }
     */
    public List<GenericOutputType> getOutput() {
        if (output == null) {
            output = new ArrayList<GenericOutputType>();
        }
        return this.output;
    }

    public boolean isSetOutput() {
        return ((this.output != null) && (!this.output.isEmpty()));
    }

    public void unsetOutput() {
        this.output = null;
    }

}
