//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.25 at 01:33:12 PM EET 
//


package ro.uti.ksme.wps.wps2.pojo.wps._2;

import ro.uti.ksme.wps.wps2.pojo.ows._2.ValueType;

import javax.xml.bind.annotation.*;


/**
 * Representation of a simple literal value (such as an integer, a real number, or a string).
 * <p>
 * <p>
 * <p>
 * String representation of the actual value (e.g., "49").
 *
 *
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.opengis.net/ows/2.0&gt;ValueType"&gt;
 *       &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="uom" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "LiteralValue")
public class LiteralValue
        extends ValueType {

    @XmlAttribute(name = "dataType")
    @XmlSchemaType(name = "anyURI")
    protected String dataType;
    @XmlAttribute(name = "uom")
    @XmlSchemaType(name = "anyURI")
    protected String uom;

    /**
     * Gets the value of the dataType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    public boolean isSetDataType() {
        return (this.dataType != null);
    }

    /**
     * Gets the value of the uom property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUom() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUom(String value) {
        this.uom = value;
    }

    public boolean isSetUom() {
        return (this.uom != null);
    }

}
