//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.25 at 01:33:12 PM EET 
//


package ro.uti.ksme.wps.wps2.pojo.wps._2;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/wps/2.0}ProcessOffering" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "processOffering"
})
@XmlRootElement(name = "ProcessOfferings")
public class ProcessOfferings {

    @XmlElement(name = "ProcessOffering", required = true)
    protected List<ProcessOffering> processOffering;

    /**
     * Ordered list of one or more full Process
     * descriptions, listed in the order in which they were requested
     * in the DescribeProcess operation request.
     * Gets the value of the processOffering property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processOffering property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessOffering().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProcessOffering }
     */
    public List<ProcessOffering> getProcessOffering() {
        if (processOffering == null) {
            processOffering = new ArrayList<ProcessOffering>();
        }
        return this.processOffering;
    }

    public boolean isSetProcessOffering() {
        return ((this.processOffering != null) && (!this.processOffering.isEmpty()));
    }

    public void unsetProcessOffering() {
        this.processOffering = null;
    }

}
