//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.25 at 01:33:12 PM EET 
//


package ro.uti.ksme.wps.wps2.pojo.wps._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * The process summary consists of descriptive elements at the process level,
 * the process profiles and the service-specific properties.
 * The process summary is not specific about process inputs and outputs.
 *
 *
 * <p>Java class for ProcessSummaryType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ProcessSummaryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/wps/2.0}DescriptionType"&gt;
 *       &lt;attGroup ref="{http://www.opengis.net/wps/2.0}processPropertiesAttributes"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessSummaryType")
public class ProcessSummaryType
        extends DescriptionType {

    @XmlAttribute(name = "jobControlOptions", required = true)
    protected List<String> jobControlOptions;
    @XmlAttribute(name = "outputTransmission")
    protected List<DataTransmissionModeType> outputTransmission;
    @XmlAttribute(name = "processVersion")
    protected String processVersion;
    @XmlAttribute(name = "processModel")
    protected String processModel;

    /**
     * Gets the value of the jobControlOptions property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jobControlOptions property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJobControlOptions().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getJobControlOptions() {
        if (jobControlOptions == null) {
            jobControlOptions = new ArrayList<String>();
        }
        return this.jobControlOptions;
    }

    public boolean isSetJobControlOptions() {
        return ((this.jobControlOptions != null) && (!this.jobControlOptions.isEmpty()));
    }

    public void unsetJobControlOptions() {
        this.jobControlOptions = null;
    }

    /**
     * Gets the value of the outputTransmission property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputTransmission property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputTransmission().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataTransmissionModeType }
     */
    public List<DataTransmissionModeType> getOutputTransmission() {
        if (outputTransmission == null) {
            outputTransmission = new ArrayList<DataTransmissionModeType>();
        }
        return this.outputTransmission;
    }

    public boolean isSetOutputTransmission() {
        return ((this.outputTransmission != null) && (!this.outputTransmission.isEmpty()));
    }

    public void unsetOutputTransmission() {
        this.outputTransmission = null;
    }

    /**
     * Gets the value of the processVersion property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProcessVersion() {
        return processVersion;
    }

    /**
     * Sets the value of the processVersion property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProcessVersion(String value) {
        this.processVersion = value;
    }

    public boolean isSetProcessVersion() {
        return (this.processVersion != null);
    }

    /**
     * Gets the value of the processModel property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getProcessModel() {
        if (processModel == null) {
            return "native";
        } else {
            return processModel;
        }
    }

    /**
     * Sets the value of the processModel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setProcessModel(String value) {
        this.processModel = value;
    }

    public boolean isSetProcessModel() {
        return (this.processModel != null);
    }

}
