//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.08 at 01:22:16 PM EEST 
//


package ro.uti.ksme.wps.wps2_server.pojo.ows._2;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{http://www.opengis.net/ows/2.0}HTTP"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "http"
})
@XmlRootElement(name = "DCP")
public class DCP {

    @XmlElement(name = "HTTP")
    protected HTTP http;

    /**
     * Gets the value of the http property.
     *
     * @return possible object is
     * {@link HTTP }
     */
    public HTTP getHTTP() {
        return http;
    }

    /**
     * Sets the value of the http property.
     *
     * @param value allowed object is
     *              {@link HTTP }
     */
    public void setHTTP(HTTP value) {
        this.http = value;
    }

    public boolean isSetHTTP() {
        return (this.http != null);
    }

}
